// Original compact reflections for the single-line screensaver layout.
export const quoteLibrary: [text: string, verbs: string][] = [
  ['Progress becomes visible when patient effort outlasts the need for immediate reassurance.', 'becomes outlasts'],
  ['You can change direction without pretending the previous journey was entirely wasted.', 'can change pretending was wasted'],
  ['The questions you ask quietly often reveal what your ambitions have overlooked.', 'ask reveal have overlooked'],
  ['Confidence grows when your actions begin to agree with your considered values.', 'grows begin agree'],
  ['A thoughtful pause can prevent a hurried decision from becoming a lasting burden.', 'can prevent becoming'],
  ['What you consistently practice will eventually matter more than what you occasionally promise.', 'practice will matter promise'],
  ['Clarity arrives when you stop defending assumptions and start examining their consequences.', 'arrives stop defending start examining'],
  ['You need not solve everything today to make tomorrow slightly more manageable.', 'need solve make'],
  ['The courage to reconsider a belief can be stronger than the confidence to defend it.', 'reconsider can be defend'],
  ['Attention is a quiet investment whose returns become visible through deliberate choices.', 'is become'],
  ['A difficult season may teach you which commitments deserve your limited energy.', 'may teach deserve'],
  ['Your next useful step does not require a complete map of the future.', 'does require'],
  ['Patience becomes productive when it supports action instead of postponing necessary decisions.', 'becomes supports postponing'],
  ['You can remain ambitious while allowing your pace to reflect your actual circumstances.', 'can remain allowing reflect'],
  ['The work that matters often begins before anyone notices its significance.', 'matters begins notices'],
  ['Wisdom includes knowing when another conversation is worth more than another conclusion.', 'includes knowing is'],
  ['Small improvements endure when they fit naturally into the life you actually live.', 'endure fit live'],
  ['You will understand your priorities better by noticing what repeatedly claims your attention.', 'will understand noticing claims'],
  ['A generous interpretation can create room for understanding without abandoning clear boundaries.', 'can create abandoning'],
  ['Your standards should guide your effort without turning every mistake into a verdict.', 'should guide turning'],
  ['Meaningful change begins when discomfort becomes a question rather than an excuse.', 'begins becomes'],
  ['You can appreciate your progress without insisting that the journey is complete.', 'can appreciate insisting is'],
  ['The most useful insight is often the one you are willing to act upon.', 'is are act'],
  ['Consistency depends less on intensity than on returning after an imperfect day.', 'depends returning'],
  ['A clear boundary protects the attention that your most important work requires.', 'protects requires'],
  ['You may discover a better answer by questioning the problem you were given.', 'may discover questioning were given'],
  ['Growth asks you to release explanations that once helped but now hold you back.', 'asks release helped hold'],
  ['The quality of your decisions improves when curiosity survives the discomfort of uncertainty.', 'improves survives'],
  ['You can value another perspective without surrendering responsibility for your own judgment.', 'can value surrendering'],
  ['A modest beginning is still a beginning when the direction has been thoughtfully chosen.', 'is has been chosen'],
  ['Discipline creates freedom when it reduces the decisions that repeatedly exhaust your attention.', 'creates reduces exhaust'],
  ['You should measure progress against your purpose, not against someone else’s visible pace.', 'should measure'],
  ['The habit of listening carefully can reveal opportunities that urgency would otherwise conceal.', 'listening can reveal would conceal'],
  ['A setback becomes informative when you examine it without making it your identity.', 'becomes examine making'],
  ['Your future benefits from decisions that your present comfort would prefer to avoid.', 'benefits would prefer avoid'],
  ['You can pursue excellence while remembering that perfection rarely provides a practical starting point.', 'can pursue remembering provides'],
  ['Understanding deepens when you can explain an idea without hiding behind its vocabulary.', 'deepens can explain hiding'],
  ['The promises you keep to yourself gradually become the foundation of reliable confidence.', 'keep become'],
  ['A meaningful goal should leave room for the person you are becoming.', 'should leave are becoming'],
  ['You do not need universal approval to make a thoughtful and responsible choice.', 'do need make'],
  ['Perspective changes when you consider the cost of remaining exactly where you are.', 'changes consider remaining are'],
  ['The best use of experience is to improve judgment rather than preserve resentment.', 'is improve preserve'],
  ['You may need less certainty than you imagine and more willingness than you expect.', 'may need imagine expect'],
  ['A reliable routine carries your intentions through the days when enthusiasm cannot.', 'carries cannot'],
  ['Progress often follows the moment you replace a vague concern with a specific question.', 'follows replace'],
  ['You can learn from criticism without allowing every opinion to become an instruction.', 'can learn allowing become'],
  ['The strength of an idea grows when it can survive an honest challenge.', 'grows can survive'],
  ['A quieter pace can help you notice what constant urgency keeps obscuring.', 'can help notice keeps obscuring'],
  ['Your choices become clearer when you distinguish a genuine need from a familiar habit.', 'become distinguish'],
  ['You should protect the conditions that allow your best attention to emerge.', 'should protect allow emerge'],
  ['Resilience develops through recovery as much as through the willingness to continue.', 'develops continue'],
  ['A careful question can open possibilities that a confident assumption would close.', 'can open would close'],
  ['You can be grateful for stability while still making room for thoughtful change.', 'can be making'],
  ['The distance between intention and action narrows when your next step becomes specific.', 'narrows becomes'],
  ['A lasting contribution often depends on work that offers little immediate recognition.', 'depends offers'],
  ['You may move forward before you fully understand what the experience will mean.', 'may move understand will mean'],
  ['Honesty becomes useful when it is accompanied by the patience to listen.', 'becomes is accompanied listen'],
  ['The boundaries you maintain reveal which responsibilities you are prepared to honor.', 'maintain reveal are honor'],
  ['You can revise a plan without abandoning the purpose that made it worthwhile.', 'can revise abandoning made'],
  ['A difficult conversation is easier when understanding matters more than winning.', 'is matters winning'],
  ['Good judgment requires the humility to notice when familiar methods no longer fit.', 'requires notice fit'],
  ['You will see more clearly when comparison stops determining the value of your efforts.', 'will see stops determining'],
  ['The ability to begin again is a skill that patient practice can strengthen.', 'begin is can strengthen'],
  ['A useful ambition gives direction without demanding that every moment prove your worth.', 'gives demanding prove'],
  ['You can slow down long enough to choose what deserves to move faster.', 'can slow choose deserves move'],
  ['The lessons you remember are often those you have tested against ordinary life.', 'remember are have tested'],
  ['A small act of preparation can make a difficult moment considerably less demanding.', 'can make'],
  ['You should allow new evidence to change conclusions that confidence alone cannot justify.', 'should allow change cannot justify'],
  ['Purpose becomes practical when it influences the choices you make on ordinary days.', 'becomes influences make'],
  ['The willingness to repair a mistake matters more than the appearance of never failing.', 'repair matters failing'],
  ['You can approach uncertainty with curiosity instead of treating it as a personal failure.', 'can approach treating'],
  ['A balanced life requires noticing what success might quietly be asking you to sacrifice.', 'requires noticing might be asking sacrifice'],
  ['Your understanding expands when you remain interested in what you have not yet learned.', 'expands remain have learned'],
  ['You may find direction by removing commitments that no longer serve your deeper intentions.', 'may find removing serve'],
  ['The patience to finish carefully is part of the courage to begin.', 'finish is begin'],
  ['A good decision considers both the immediate benefit and the responsibility that follows.', 'considers follows'],
  ['You can remain open to possibility while being honest about your current limitations.', 'can remain being'],
  ['The work of becoming reliable begins with promises small enough to keep.', 'becoming begins keep'],
  ['A clearer future often starts with a more honest description of the present.', 'starts'],
  ['You should question expectations that demand more performance than meaningful contribution.', 'should question demand'],
  ['Learning becomes lasting when reflection connects an experience to a change in behavior.', 'becomes connects'],
  ['The most productive pause is one that restores your ability to choose deliberately.', 'is restores choose'],
  ['You can acknowledge disappointment without letting it decide the limits of your future.', 'can acknowledge letting decide'],
  ['A strong foundation is built through habits that remain useful when circumstances change.', 'is built remain change'],
  ['Your effort becomes more effective when you understand what you are trying to improve.', 'becomes understand are trying improve'],
  ['You may discover that a gentler approach produces a more sustainable kind of strength.', 'may discover produces'],
  ['The courage to ask for help can protect the work you care about.', 'ask can protect care'],
  ['A thoughtful response begins with understanding what the situation actually requires of you.', 'begins understanding requires'],
  ['You can celebrate a milestone without allowing it to become your final destination.', 'can celebrate allowing become'],
  ['The choices that shape your character are often made without an audience.', 'shape are made'],
  ['A useful perspective leaves room for complexity without making responsible action impossible.', 'leaves making'],
  ['You should remember that improvement rarely arrives in the order you initially expected.', 'should remember arrives expected'],
  ['Integrity grows when your private decisions remain consistent with your public commitments.', 'grows remain'],
  ['The ability to notice enough can be as valuable as the drive to achieve more.', 'notice can be achieve'],
  ['You can respect tradition while asking whether its assumptions still serve the present.', 'can respect asking serve'],
  ['A demanding task becomes manageable when you separate the next action from the entire outcome.', 'becomes separate'],
  ['Your attention is better spent on useful questions than on rehearsing unlikely disasters.', 'is spent rehearsing'],
  ['You may need to outgrow a familiar role before discovering a more honest direction.', 'may need outgrow discovering'],
  ['The meaning of progress changes when you include the quality of your daily experience.', 'changes include'],
  ['A well-chosen commitment gives your energy somewhere worthwhile to return each day.', 'gives return'],
  ['You can disagree clearly while leaving the other person enough dignity to reconsider.', 'can disagree leaving reconsider'],
  ['The value of knowledge grows when you use it to improve someone else’s understanding.', 'grows use improve'],
  ['A calm mind is not empty of concerns; it is less governed by them.', 'is is governed'],
  ['You should give important decisions enough space to become clearer than your immediate reaction.', 'should give become'],
  ['Trust develops when your actions remain understandable even when the outcome is uncertain.', 'develops remain is'],
  ['The next chapter may require a different strength from the one that brought you here.', 'may require brought'],
  ['You can make room for rest without treating ambition as something to abandon.', 'can make treating abandon'],
  ['A meaningful improvement solves a real difficulty instead of merely creating a better appearance.', 'solves creating'],
  ['Your priorities become visible through the opportunities you are willing to decline.', 'become are decline'],
  ['You may understand a challenge differently after giving yourself permission to recover.', 'may understand giving recover'],
  ['The discipline of reflection keeps experience from becoming repetition without learning.', 'keeps becoming learning'],
  ['A wise adjustment preserves the purpose while changing the method that no longer works.', 'preserves changing works'],
  ['You can choose a smaller step when taking it consistently will move you further.', 'can choose taking will move'],
  ['The freedom to change your mind comes with responsibility for explaining your reasons.', 'change comes explaining'],
  ['A patient observer notices patterns that a hurried participant may repeatedly overlook.', 'notices may overlook'],
  ['You should invest in habits that make good choices easier when your energy is limited.', 'should invest make is limited'],
  ['Confidence becomes steadier when it rests on preparation rather than favorable circumstances.', 'becomes rests'],
  ['The future remains open even when your current perspective cannot reveal every possibility.', 'remains cannot reveal'],
  ['You can accept an imperfect beginning without lowering the care you bring to the work.', 'can accept lowering bring'],
  ['A thoughtful life is shaped by what you repeatedly choose to notice and nurture.', 'is shaped choose notice nurture'],
];
